name: flashcards_flutter
version: 0.0.1
description: Flutter view of flashcards.

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'
  flutter: '>=0.1.4 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: '^0.1.0'
  flashcards_logic:
    path: ../logic

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: 'Lobster'
      fonts:
        - asset: assets/fonts/lobster-v20-latin-regular.ttf
          weight: 400
